import React, { useEffect, useMemo, useState } from "react";
import { collection, deleteDoc, doc, onSnapshot, serverTimestamp, setDoc } from "firebase/firestore";
import { CalendarCheck, Download, ExternalLink, Plus, QrCode, RefreshCw, Save, Search, Trash2 } from "lucide-react";
import { DEFAULT_SALON_EVENT, formatSalonDateTime, normalizeSalonEvent, SALON_APPLICATION_STATUSES, SALON_EVENT_COLLECTION, toDateTimeLocalValue } from "../../constants/salon";
import { callSalonFunction } from "../../lib/salonApi";

const fieldClass = "mt-2 w-full rounded-xl border-2 border-zinc-200 bg-white px-3 py-2.5 text-sm font-bold outline-none focus:border-[#004aad]";
const labelClass = "block text-[11px] font-black text-zinc-600";
const toSlug = (value) => String(value || "salon").trim().toLowerCase().replace(/[^a-z0-9가-힣]+/g, "-").replace(/(^-|-$)/g, "") || `salon-${Date.now()}`;
const phoneDisplay = (value) => String(value || "").replace(/(\d{3})(\d{3,4})(\d{4})/, "$1-$2-$3");
const getStatusLabel = (status) => SALON_APPLICATION_STATUSES.find((item) => item.value === status)?.label || status;
const asCsv = (items) => {
  const rows = [["이름", "연락처", "이메일", "닉네임", "상태", "QR", "확정알림", "체크인", "체크인시간", "환영알림"]];
  items.forEach((item) => rows.push([item.applicantName, item.phone, item.email, item.nickname, getStatusLabel(item.status), item.qrTokenHash ? "발급" : "미발급", item.approvalNotificationStatus, item.checkedInAt ? "완료" : "미입장", item.checkedInAt?.toDate?.()?.toISOString?.() || item.checkedInAt || "", item.welcomeNotificationStatus]));
  return rows.map((row) => row.map((cell) => `"${String(cell ?? "").replaceAll('"', '""')}"`).join(",")).join("\n");
};

const EventEditor = ({ draft, setDraft, onSave, onDelete, saving }) => {
  const update = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  const nested = (group, key, value) => setDraft((current) => ({ ...current, [group]: { ...current[group], [key]: value } }));
  const notification = (key, value) => nested("notificationSettings", key, value);
  const checkIn = (key, value) => nested("checkInSettings", key, value);
  const links = (key, value) => nested("links", key, value);
  const formField = (field, key, value) => setDraft((current) => ({ ...current, formSettings: { ...current.formSettings, fields: { ...current.formSettings.fields, [field]: { ...current.formSettings.fields[field], [key]: value } } } }));
  const privacy = (key, value) => setDraft((current) => ({ ...current, formSettings: { ...current.formSettings, privacy: { ...current.formSettings.privacy, [key]: value } } }));
  const setCustomFields = (customFields) => setDraft((current) => ({ ...current, formSettings: { ...current.formSettings, customFields } }));
  return <div className="rounded-[28px] border-2 border-zinc-900 bg-white p-5 shadow-[4px_4px_0px_#000] md:p-7">
    <div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#004aad]">Event editor</p><h3 className="mt-1 text-2xl font-black">SALON 행사 설정</h3></div>{draft.id && <button type="button" onClick={onDelete} className="rounded-full border border-red-200 p-3 text-red-600"><Trash2 size={17} /></button>}</div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2">
      <label className={labelClass}>제목 *<input className={fieldClass} value={draft.title} onChange={(e) => update("title", e.target.value)} /></label>
      <label className={labelClass}>공유 slug *<input className={fieldClass} value={draft.slug} onChange={(e) => update("slug", e.target.value)} placeholder="july-salon" /></label>
      <label className={labelClass}>부제<input className={fieldClass} value={draft.subtitle} onChange={(e) => update("subtitle", e.target.value)} /></label>
      <label className={labelClass}>포스터 이미지 URL<input className={fieldClass} value={draft.posterImageUrl} onChange={(e) => update("posterImageUrl", e.target.value)} /></label>
      <label className={labelClass}>신청 버튼 문구<input className={fieldClass} value={draft.applicationButtonText} onChange={(e) => update("applicationButtonText", e.target.value)} /></label>
      <label className={`${labelClass} sm:col-span-2`}>소개<textarea className={`${fieldClass} min-h-28`} value={draft.description} onChange={(e) => update("description", e.target.value)} /></label>
      <label className={labelClass}>상태<select className={fieldClass} value={draft.status} onChange={(e) => update("status", e.target.value)}><option value="draft">초안</option><option value="open">모집 중</option><option value="closed">마감</option><option value="archived">보관</option></select></label>
      <label className={labelClass}>정원 (0=제한 없음)<input type="number" min="0" className={fieldClass} value={draft.capacity} onChange={(e) => update("capacity", Number(e.target.value || 0))} /></label>
      {[['applicationStartAt','모집 시작'],['applicationEndAt','모집 종료'],['eventStartAt','행사 시작'],['eventEndAt','행사 종료']].map(([key,label]) => <label key={key} className={labelClass}>{label}<input type="datetime-local" className={fieldClass} value={toDateTimeLocalValue(draft[key])} onChange={(e) => update(key, e.target.value)} /></label>)}
      <label className={labelClass}>장소명<input className={fieldClass} value={draft.venueName} onChange={(e) => update("venueName", e.target.value)} /></label><label className={labelClass}>주소<input className={fieldClass} value={draft.venueAddress} onChange={(e) => update("venueAddress", e.target.value)} /></label>
      <label className={labelClass}>오늘의 프로그램 URL<input className={fieldClass} value={draft.links.programUrl} onChange={(e) => links("programUrl", e.target.value)} /></label><label className={labelClass}>온라인 방명록 URL<input className={fieldClass} value={draft.links.guestbookUrl} onChange={(e) => links("guestbookUrl", e.target.value)} /></label><label className={labelClass}>인스타그램 URL<input className={fieldClass} value={draft.links.instagramUrl} onChange={(e) => links("instagramUrl", e.target.value)} /></label>
      <label className={labelClass}>QR 만료 시각<input type="datetime-local" className={fieldClass} value={toDateTimeLocalValue(draft.checkInSettings.qrExpiresAt)} onChange={(e) => checkIn("qrExpiresAt", e.target.value)} /></label>
      <label className={labelClass}>체크인 시작<input type="datetime-local" className={fieldClass} value={toDateTimeLocalValue(draft.checkInSettings.checkInStartAt)} onChange={(e) => checkIn("checkInStartAt", e.target.value)} /></label><label className={labelClass}>체크인 종료<input type="datetime-local" className={fieldClass} value={toDateTimeLocalValue(draft.checkInSettings.checkInEndAt)} onChange={(e) => checkIn("checkInEndAt", e.target.value)} /></label>
      <label className={labelClass}>입장 완료 화면 제목<input className={fieldClass} value={draft.checkInSettings.welcomeScreenTitle} onChange={(e) => checkIn("welcomeScreenTitle", e.target.value)} /></label><label className={labelClass}>입장 완료 화면 안내<input className={fieldClass} value={draft.checkInSettings.welcomeScreenMessage} onChange={(e) => checkIn("welcomeScreenMessage", e.target.value)} /></label>
      <label className={labelClass}>확정 알림 템플릿 ID<input className={fieldClass} value={draft.notificationSettings.approvalTemplateId} onChange={(e) => notification("approvalTemplateId", e.target.value)} /></label><label className={labelClass}>환영 알림 템플릿 ID<input className={fieldClass} value={draft.notificationSettings.welcomeTemplateId} onChange={(e) => notification("welcomeTemplateId", e.target.value)} /></label>
      <label className={`${labelClass} sm:col-span-2`}>확정 알림 문구<textarea className={`${fieldClass} min-h-20`} value={draft.notificationSettings.approvalMessage} onChange={(e) => notification("approvalMessage", e.target.value)} /></label><label className={`${labelClass} sm:col-span-2`}>환영 알림 문구<textarea className={`${fieldClass} min-h-20`} value={draft.notificationSettings.welcomeMessage} onChange={(e) => notification("welcomeMessage", e.target.value)} /></label>
      <label className="flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={draft.isVisible} onChange={(e) => update("isVisible", e.target.checked)} /> 공개</label><label className="flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={draft.isFeatured} onChange={(e) => update("isFeatured", e.target.checked)} /> 메인 강조</label><label className="flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={draft.checkInSettings.enabled} onChange={(e) => checkIn("enabled", e.target.checked)} /> 현장 체크인 사용</label><label className="flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={draft.notificationSettings.approvalEnabled} onChange={(e) => notification("approvalEnabled", e.target.checked)} /> 확정 알림 사용</label><label className="flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={draft.notificationSettings.welcomeEnabled} onChange={(e) => notification("welcomeEnabled", e.target.checked)} /> 환영 알림 사용</label>
    </div>
    <div className="mt-7 rounded-[22px] bg-zinc-100 p-4"><div className="flex items-center justify-between"><h4 className="font-black">신청 양식 필드</h4><button type="button" onClick={() => setCustomFields([...(draft.formSettings.customFields || []), { id: `custom-${Date.now()}`, label: "추가 질문", type: "text", required: false }])} className="rounded-full bg-white px-3 py-2 text-xs font-black"><Plus size={13} className="mr-1 inline" />질문 추가</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(draft.formSettings.fields).map(([key, field]) => <div key={key} className="rounded-2xl bg-white p-3"><input value={field.label} onChange={(e) => formField(key, "label", e.target.value)} className="w-full border-b pb-2 text-sm font-black outline-none" /><div className="mt-3 flex gap-4 text-xs font-bold"><label><input type="checkbox" checked={field.enabled} onChange={(e) => formField(key, "enabled", e.target.checked)} /> 사용</label><label><input type="checkbox" checked={field.required} onChange={(e) => formField(key, "required", e.target.checked)} /> 필수</label></div></div>)}</div>{(draft.formSettings.customFields || []).map((field, index) => <div key={field.id} className="mt-3 grid gap-2 rounded-2xl bg-white p-3 sm:grid-cols-[1fr_0.5fr_auto_auto]"><input value={field.label} onChange={(e) => setCustomFields(draft.formSettings.customFields.map((item, i) => i === index ? { ...item, label: e.target.value } : item))} className="rounded-xl border px-3 py-2 text-sm font-bold" /><select value={field.type} onChange={(e) => setCustomFields(draft.formSettings.customFields.map((item, i) => i === index ? { ...item, type: e.target.value } : item))} className="rounded-xl border px-3 py-2 text-sm font-bold"><option value="text">한 줄</option><option value="textarea">긴 글</option><option value="checkbox">체크</option></select><label className="self-center text-xs font-bold"><input type="checkbox" checked={field.required} onChange={(e) => setCustomFields(draft.formSettings.customFields.map((item, i) => i === index ? { ...item, required: e.target.checked } : item))} /> 필수</label><button type="button" onClick={() => setCustomFields(draft.formSettings.customFields.filter((_, i) => i !== index))} className="text-red-600"><Trash2 size={16} /></button></div>)}
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><label className={labelClass}>개인정보 동의 제목<input className={fieldClass} value={draft.formSettings.privacy.title} onChange={(e) => privacy("title", e.target.value)} /></label><label className={labelClass}>체크박스 문구<input className={fieldClass} value={draft.formSettings.privacy.checkboxLabel} onChange={(e) => privacy("checkboxLabel", e.target.value)} /></label><label className={`${labelClass} sm:col-span-2`}>개인정보 안내문<textarea className={`${fieldClass} min-h-20`} value={draft.formSettings.privacy.body} onChange={(e) => privacy("body", e.target.value)} /></label><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={draft.formSettings.privacy.enabled} onChange={(e) => privacy("enabled", e.target.checked)} /> 개인정보 동의 사용</label><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={draft.formSettings.privacy.required} onChange={(e) => privacy("required", e.target.checked)} /> 동의 필수</label></div>
    </div>
    {((draft.notificationSettings.approvalEnabled && !draft.notificationSettings.approvalTemplateId) || (draft.notificationSettings.welcomeEnabled && !draft.notificationSettings.welcomeTemplateId)) && <p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-800">템플릿 ID가 비어 있습니다. 서버 환경변수로 설정하지 않았다면 알림톡이 실패합니다.</p>}
    <button type="button" onClick={onSave} disabled={saving || !draft.title} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#004aad] px-6 py-3 text-sm font-black text-white disabled:opacity-40"><Save size={16} />{saving ? "저장 중..." : "행사 저장"}</button>
  </div>;
};

const SalonManager = ({ db, appId, applications }) => {
  const [events, setEvents] = useState([]); const [selectedId, setSelectedId] = useState(""); const [draft, setDraft] = useState(normalizeSalonEvent(DEFAULT_SALON_EVENT)); const [saving, setSaving] = useState(false); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); const [busyId, setBusyId] = useState("");
  useEffect(() => onSnapshot(collection(db, "artifacts", appId, "public", "data", SALON_EVENT_COLLECTION), (snapshot) => setEvents(snapshot.docs.map((item) => normalizeSalonEvent({ id: item.id, ...item.data() })))), [db, appId]);
  const choose = (event) => { setSelectedId(event.id); setDraft(normalizeSalonEvent(event)); };
  const createNew = () => { setSelectedId(""); setDraft(normalizeSalonEvent(DEFAULT_SALON_EVENT)); };
  const save = async () => { setSaving(true); try { const id = draft.id || doc(collection(db, "artifacts", appId, "public", "data", SALON_EVENT_COLLECTION)).id; const current = events.find((item) => item.id === id); await setDoc(doc(db, "artifacts", appId, "public", "data", SALON_EVENT_COLLECTION, id), { ...draft, id, slug: toSlug(draft.slug || draft.title), createdAt: current?.createdAt || serverTimestamp(), updatedAt: serverTimestamp() }, { merge: true }); setSelectedId(id); setDraft((v) => ({ ...v, id })); } catch (error) { alert(error.message); } finally { setSaving(false); } };
  const remove = async () => { if (!draft.id || !window.confirm("이 SALON 행사를 삭제하시겠습니까? 참가 신청 문서는 삭제되지 않습니다.")) return; await deleteDoc(doc(db, "artifacts", appId, "public", "data", SALON_EVENT_COLLECTION, draft.id)); createNew(); };
  const selectedEvent = events.find((event) => event.id === selectedId) || (draft.id ? draft : null);
  const participants = useMemo(() => (applications || []).filter((item) => item.trackType === "salon" && (!selectedEvent || item.salonId === selectedEvent.id)).filter((item) => filter === "all" || item.status === filter).filter((item) => `${item.applicantName} ${item.phone}`.toLowerCase().includes(search.toLowerCase())), [applications, selectedEvent, filter, search]);
  const act = async (item, action, extra = {}) => { const messages = { approve: "참가 승인 및 QR을 발급하시겠습니까?\n참가 확정 알림톡이 함께 발송됩니다.", reissue: "기존 QR은 즉시 사용할 수 없게 됩니다.\n새 QR을 발급하시겠습니까?" }; if (messages[action] && !window.confirm(messages[action])) return; setBusyId(item.id); try { let result; if (["approve", "reissue", "resend"].includes(action)) result = await callSalonFunction("approve-salon-participant", { applicationId: item.id, action }); else result = await callSalonFunction("manage-salon-participant", { applicationId: item.id, action, ...extra }); if (result.passUrl && result.notification?.status === "failed") { await navigator.clipboard?.writeText(result.passUrl); alert("승인은 완료되었지만 알림톡은 실패했습니다. 새 QR 링크를 클립보드에 복사했습니다."); } } catch (error) { alert(error.message); } finally { setBusyId(""); } };
  const download = () => { const blob = new Blob(["\ufeff" + asCsv(participants)], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `unframe-salon-${selectedEvent?.slug || "all"}-participants.csv`; link.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-7">
    <div className="grid gap-5 lg:grid-cols-[0.3fr_0.7fr]"><aside className="rounded-[28px] border-2 border-zinc-900 bg-[#f6f4ee] p-4"><button onClick={createNew} className="flex w-full items-center justify-center gap-2 rounded-full bg-zinc-950 px-4 py-3 text-sm font-black text-white"><Plus size={16} /> 새 SALON</button><div className="mt-4 space-y-2">{events.map((event) => <button key={event.id} onClick={() => choose(event)} className={`w-full rounded-2xl border p-4 text-left ${selectedId === event.id ? "border-[#004aad] bg-white" : "border-zinc-200"}`}><p className="font-black">{event.title || "제목 없음"}</p><p className="mt-1 text-xs font-bold text-zinc-500">{event.status} · {formatSalonDateTime(event.eventStartAt)}</p></button>)}</div></aside><EventEditor draft={draft} setDraft={setDraft} onSave={save} onDelete={remove} saving={saving} /></div>
    <section className="rounded-[28px] border-2 border-zinc-900 bg-white p-5 shadow-[4px_4px_0px_#000]"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#004aad]">Participants</p><h3 className="mt-1 text-2xl font-black">참가자 관리</h3></div><div className="flex gap-2">{selectedEvent && <a href={`/admin/salon/check-in/${selectedEvent.id}`} className="inline-flex items-center gap-2 rounded-full bg-[#AAD004] px-4 py-2 text-xs font-black"><QrCode size={15} /> 체크인 화면</a>}<button onClick={download} className="inline-flex items-center gap-2 rounded-full border border-zinc-300 px-4 py-2 text-xs font-black"><Download size={15} /> CSV</button></div></div>
      <div className="mt-5 flex flex-wrap gap-3"><label className="relative min-w-60 flex-1"><Search size={16} className="absolute left-3 top-3 text-zinc-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="이름 또는 연락처 검색" className="w-full rounded-full border-2 border-zinc-200 py-2.5 pl-10 pr-4 text-sm font-bold" /></label><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-full border-2 border-zinc-200 px-4 text-sm font-black"><option value="all">전체 상태</option>{SALON_APPLICATION_STATUSES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead><tr className="border-b-2 border-zinc-900">{["신청자","상태","QR","확정 알림","입장","환영 알림","관리"].map((item) => <th key={item} className="px-3 py-3 font-black">{item}</th>)}</tr></thead><tbody>{participants.map((item) => <tr key={item.id} className="border-b border-zinc-100 align-top"><td className="px-3 py-4"><p className="font-black">{item.applicantName || item.nickname || "-"}</p><p className="mt-1 text-zinc-500">{phoneDisplay(item.phone)}</p></td><td className="px-3 py-4 font-black">{getStatusLabel(item.status)}</td><td className="px-3 py-4">{item.qrTokenHash ? "발급 완료" : "미발급"}</td><td className="px-3 py-4">{item.approvalNotificationStatus || "pending"}</td><td className="px-3 py-4">{item.checkedInAt ? <><b>입장 완료</b><br />{formatSalonDateTime(item.checkedInAt)}</> : "미입장"}</td><td className="px-3 py-4">{item.welcomeNotificationStatus || "pending"}</td><td className="px-3 py-4"><div className="flex max-w-[330px] flex-wrap gap-2">{item.status !== "approved" && <button disabled={busyId === item.id} onClick={() => act(item, "approve")} className="rounded-full bg-[#004aad] px-3 py-1.5 font-black text-white">승인+QR</button>}{item.status === "approved" && <><button onClick={() => act(item, "reissue")} className="rounded-full border px-3 py-1.5 font-black"><RefreshCw size={12} className="mr-1 inline" />QR 재발급</button><button onClick={() => act(item, "resend")} className="rounded-full border px-3 py-1.5 font-black">확정 알림 재발송</button></>}{["submitted","waitlisted","rejected","cancelled"].filter((status) => status !== item.status).map((status) => <button key={status} onClick={() => act(item, "status", { status })} className="rounded-full border px-3 py-1.5 font-black">{getStatusLabel(status)}</button>)}{item.checkedInAt && <button onClick={() => act(item, "resend-welcome")} className="rounded-full border px-3 py-1.5 font-black">환영 알림 재발송</button>}</div></td></tr>)}</tbody></table>{participants.length === 0 && <p className="py-10 text-center font-bold text-zinc-400">조건에 맞는 참가자가 없습니다.</p>}</div>
    </section>
  </div>;
};
export default SalonManager;
